project:
  type: website

website:
  title: "William Jackson"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects in GBA5910"
        href: marketing-analytics.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

